# Generated by Django 4.0.4 on 2022-05-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=1)),
                ('semester', models.IntegerField(max_length=1)),
                ('ects', models.IntegerField(max_length=2)),
                ('lective_year', models.IntegerField(max_length=4)),
            ],
        ),
    ]
