# Generated by Django 4.0.4 on 2022-05-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_person_alter_subject_ects_alter_subject_lective_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('trailer_url', models.CharField(max_length=100)),
            ],
        ),
    ]
