# Generated by Django 4.0.4 on 2022-05-24 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='linkedin',
            new_name='linkedin_url',
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 1, 39, 29, 72460)),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 1, 39, 29, 72460)),
        ),
    ]
