# Generated by Django 4.0.4 on 2022-05-24 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_linkedin_person_linkedin_url_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 19, 1, 13, 294758, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 19, 1, 13, 294758, tzinfo=utc)),
        ),
    ]
