# Generated by Django 4.0.4 on 2022-05-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_project_end_date_alter_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='Description', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='image.png', upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='project',
            name='trailer_url',
            field=models.URLField(default='http://youtube.com/'),
        ),
    ]
