# Generated by Django 4.0.4 on 2022-05-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_project_end_date_remove_project_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='image.png', upload_to='portfolio\\static\\portfolio\\images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='Name', max_length=50),
        ),
    ]
