# Generated by Django 4.0.4 on 2022-05-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(default='image.png', max_length=100),
        ),
    ]
