# Generated by Django 4.0.4 on 2022-06-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HTML', max_length=50)),
                ('description', models.CharField(default='Description', max_length=500)),
                ('link', models.URLField(default='https://wikipedia.org')),
            ],
        ),
    ]
