# Generated by Django 4.0.4 on 2022-06-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_laboratory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(default='Laboratory', max_length=50),
        ),
    ]
