# Generated by Django 4.0.4 on 2022-06-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='default_project.png', upload_to='images/projects'),
        ),
    ]
