# Generated by Django 4.0.4 on 2022-06-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='link',
            field=models.URLField(default='https://www.ulusofona.pt/'),
        ),
    ]
