# Generated by Django 4.0.4 on 2022-06-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_post_author_post_date_post_description_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='description',
            field=models.TextField(default='Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.TextField(default='Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(default='Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='webtechnology',
            name='description',
            field=models.TextField(default='Description', max_length=500),
        ),
    ]
