# Generated by Django 4.0.4 on 2022-06-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_alter_post_author_alter_post_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=50)),
                ('author', models.CharField(default='Author', max_length=50)),
                ('advisor', models.CharField(default='Advisor', max_length=50)),
                ('resume', models.TextField(default='Resume', max_length=500)),
                ('github_link', models.URLField(default='https://github.com', max_length=256)),
                ('youtube_link', models.URLField(default='https://youtube.com', max_length=256)),
                ('image', models.ImageField(default='tfc/images/default.png', upload_to='tfc/images/')),
                ('report', models.FileField(upload_to='')),
            ],
        ),
    ]
