# Generated by Django 4.0.4 on 2022-06-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_tfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfc',
            name='report',
            field=models.FileField(blank='True', upload_to='tfc/reports/'),
        ),
    ]
