# Generated by Django 4.0.4 on 2022-06-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_alter_tfc_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfc',
            name='report',
        ),
        migrations.AddField(
            model_name='tfc',
            name='report_link',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='advisor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='github_link',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='image',
            field=models.ImageField(blank=True, upload_to='tfc/images/'),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='resume',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='youtube_link',
            field=models.URLField(default='', max_length=256),
        ),
    ]
