# Generated by Django 4.0.4 on 2022-06-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_remove_tfc_report_tfc_report_link_alter_tfc_advisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfc',
            name='image',
            field=models.FileField(blank=True, upload_to='tfc/images/'),
        ),
    ]
