# Generated by Django 4.0.4 on 2022-06-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0037_alter_tfc_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='name',
        ),
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='new',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='link',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='link',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='new',
            name='link',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin_url',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='trailer_url',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='webtechnology',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='webtechnology',
            name='link',
            field=models.URLField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='webtechnology',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
