# Generated by Django 4.0.4 on 2022-06-17 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0038_remove_new_name_new_image_new_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='title',
            new_name='name',
        ),
    ]
