# Generated by Django 4.0.4 on 2022-06-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0040_rename_name_new_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='title',
            new_name='name',
        ),
    ]
